---
title: "test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MCL)
library(igraph)
library(RJSONIO)
```

## For Undirected Graph
```{r}
### Generate adjacency matrix of undirected graph
adjacency <- as.matrix(read.csv("test_graph.csv",sep=",",header=FALSE))
ids <- read.csv("test_ids.csv",header=F)$V1
### Plot graph (requires package igraph)
gu <- graph.adjacency(adjacency, mode="undirected" )
plot(gu)
```



```{r}
### Allow clusters of size 1
mcl(x = adjacency, addLoops=TRUE, ESM = TRUE)
result <- mcl(x = adjacency, addLoops = TRUE, allow1 = TRUE)
result
```

```{r}
df <- data.frame(ids, result$Cluster)
initial_c = -1
clusters = list()
for (i in 1:length(result$Cluster)){
  temp = result$Cluster[i]
  
  if (initial_c == temp){
     listtemp = clusters[[temp]]
     clusters[[temp]] <- c(listtemp, ids[i])
  }
  else{
    clusters[[temp]] <- c()
    clusters[[temp]] <- c(ids[i])
    initial_c = temp
  }
}
```


```{r}
exportJson <- toJSON(clusters)
write(exportJson, "test1.json")
```



